FROM python:3.9-slim

WORKDIR /app


# Copy requirements first from its location relative to the build context
COPY test-mqtt/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code and the json folder
COPY test-mqtt/mqtt_consumer.py .
COPY test-mqtt/controller.py .

COPY json_files ./json_files/

CMD ["python", "controller.py"]
