{
 "title": "database_logger dashboard",
 "tags": [
  "ETL",
  "Python",
  "kaka",
  "SQL"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job_var",
    "query": {}
   },
   {
    "name": "component_var",
    "query": {}
   },
   {
    "name": "stage_var",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Error count per stage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(stage)(count_over_time({job=\"$job_var\", component=\"$component_var\", stage=~\".+\"} |~ \"(?i)error|CRITICAL\" [5m]))\r\n"
    }
   ]
  },
  {
   "title": "Most active stages per component",
   "type": "piechart",
   "description": "logs distribution in pie chart last 5m",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (stage) (count_over_time({job=\"$job_var\", component=\"$component_var\"}[5m])) \r\n"
    }
   ]
  },
  {
   "title": "count of error logs in stage (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=~\"$job_var\", component=~\"$component_var\",stage=~\"$stage_var\"} |~ \"CRITICAL|ERROR\" [5m])\r\n"
    }
   ]
  },
  {
   "title": "logs distribution by level",
   "type": "piechart",
   "description": "logs distribution in pie chart last 5m",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"$job_var\", component=\"$component_var\",stage=\"$stage_var\"}[5m])) \r\n"
    }
   ]
  },
  {
   "title": "Logs in Tabular",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job_var\", component=\"$component_var\"} | json "
    }
   ]
  },
  {
   "title": "Error percentage by level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (log_type) (\r\n  label_replace(\r\n    sum(\r\n      count_over_time({job=\"$job_var\", component=\"$component_var\", stage=\"$stage_var\", level=~\"CRITICAL|ERROR\"} [$__range])\r\n    ) or vector(0),\r\n    \"log_type\", \"logs of critical/Error\", \"level\", \".*\"\r\n  )\r\n)\r\n"
    },
    {
     "direction": "backward",
     "expr": "sum by (log_type) (\r\n  label_replace(\r\n    sum(\r\n      count_over_time({job=\"$job_var\", component=\"$component_var\", stage=\"$stage_var\", level=~\".+\"} [$__range])\r\n    ) or vector(0),\r\n    \"log_type\", \"Total Logs\", \"level\", \".*\"\r\n  )\r\n)\r\n"
    },
    {
     "direction": "backward",
     "expr": "sum by (log_type) ( \r\n  label_replace(\r\n    (\r\n      sum(count_over_time({job=\"$job_var\", component=\"$component_var\", stage=\"$stage_var\", level=~\"CRITICAL|ERROR\"} [$__range]))\r\n      /\r\n      (sum(count_over_time({job=\"$job_var\", component=\"$component_var\", stage=\"$stage_var\", level=~\".+\"} [$__range])) or vector(1)) * 100\r\n    ) or vector(0),\r\n    \"log_type\", \"Percentage of critical/Error\", \"level\", \".*\"\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Log Volume by Component (Bar Chart)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=~\"$job_var\"}[5m])) by (component)\r\n"
    }
   ]
  },
  {
   "title": "log volume over 5m",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(stage)(count_over_time({job=\"$job_var\", component=\"$component_var\",stage=~\".+\"}[5m])) or vector(0)\r\n"
    }
   ]
  }
 ]
}